##
# default build dir
##
kp_build_dir: "{{ working_dir }}"

##
# default temp dir
##
kp_tmp_dir: "/tmp"


gitlab_ci_yaml_path: "{{ kp_build_dir }}/.gitlab-ci.yml"
readme_path: "{{ kp_build_dir }}/README.MD"
makefile_path: "{{ kp_build_dir }}/Makefile"

project_version: "{{ lookup('file', working_dir ~ '/VERSION') }}"

##
# default extension for vars_file
##
keployr_vars_file_extension: "yaml"

##
# dir for vars_file
##
keployr_vars_file_dir: ""

##
# artifacts source root dir
##
working_dir: "{{ lookup('env', 'PWD') }}"


##
# Full git URL (with scheme / auth credentials)
##
keployr_git_url: "{{ lookup('env', 'KEPLOYR_GIT_URL') }}"

##
# git branch to use (must exist!)
##
keployr_git_branch: "{{ lookup('env', 'KEPLOYR_GIT_BRANCH') | default('develop', True) }}"

##
# git user to configure
##
keployr_git_user: ""
keployr_git_user_email: ""
keployr_git_commit_message: "Update stack {{ keployr_stack }} - {{ lookup('env', 'CI_COMMIT_SHORT_SHA') }}"

##
# working dir (git clone destination)
##
keployr_tmp_project_dir: "{{ kp_tmp_dir }}/keployr_deploy"


##
# relative destination path
##
keployr_dst_path: "{{ keployr_env }}/{{ keployr_stack }}"

##
# apps definition gitops dirname
##
keployr_gitops_apps_dirname: gitops-apps

##
# relative destination path of gitops apps
##
keployr_gitops_apps_dst_path: "{{ keployr_env }}/{{ keployr_gitops_apps_dirname }}"

##
# gitops apps manifest filename
##
keployr_gitops_apps_filename: "{{ keployr_stack }}-apps.yaml"

##
# source full path
##
keployr_src_fullpath: "{{ build_dir }}/{{ keployr_env }}/{{ keployr_stack }}"
keployr_src_gitops_apps_fullpath: "{{ keployr_src_fullpath }}/{{ keployr_gitops_apps_filename }}"

keployr_dst_fullpath: "{{ keployr_tmp_project_dir }}/{{ keployr_dst_path }}"
keployr_dst_gitops_apps_fullpath: "{{ keployr_tmp_project_dir }}/{{ keployr_gitops_apps_dst_path }}"

##
# notes MD
##
keployr_note_template: notes.md.j2
keployr_note_filename: notes.md
keployr_note_fullpath: "{{ keployr_dst_fullpath }}/{{ keployr_note_filename }}"