---

##
# working dir to build stuff
##
kp_build_dir: "./build/{{ kp_env }}"

##
# default temp dir
##
kp_tmp_dir: "/tmp"


gitlab_ci_yaml_path: "{{ kp_build_dir }}/.gitlab-ci.yml"
readme_path: "{{ kp_build_dir }}/README.MD"
makefile_path: "{{ kp_build_dir }}/Makefile"

##
# default extension for vars_file
##
kp_vars_file_extension: "yaml"

##
# dir for vars_file
##
kp_vars_file_dir: ""

##
# Full git URL (with scheme / auth credentials)
##
kp_git_url: "{{ lookup('env', 'KEPLOYR_GIT_URL') }}"

##
# git branch to use (must exist!)
##
kp_git_branch: "{{ lookup('env', 'KEPLOYR_GIT_BRANCH') | default('develop', True) }}"

##
# git user to configure
##
kp_git_user: ""
kp_git_user_email: ""
kp_git_commit_message: "Update stack {{ kp_stack }} - {{ lookup('env', 'CI_COMMIT_SHORT_SHA') }}"

##
# working dir (git clone destination)
##
kp_tmp_project_dir: "{{ kp_tmp_dir }}/kp_deploy"


##
# relative destination path
##
kp_dst_path: "{{ kp_env }}/{{ kp_stack }}"

##
# apps definition gitops dirname
##
kp_gitops_apps_dirname: gitops-apps

##
# relative destination path of gitops apps
##
kp_gitops_apps_dst_path: "{{ kp_env }}/{{ kp_gitops_apps_dirname }}"

##
# gitops apps manifest filename
##
kp_gitops_apps_filename: "{{ kp_stack }}-apps.yaml"

##
# source (aka build)
##

kp_gitops_apps_file: "{{ kp_stack }}-apps.yaml"
kp_gitops_apps_build_path: "{{ kp_build_dir }}/{{ kp_gitops_apps_file }}"


kp_dst_fullpath: "{{ kp_tmp_project_dir }}/{{ kp_dst_path }}"
kp_dst_gitops_apps_fullpath: "{{ kp_tmp_project_dir }}/{{ kp_gitops_apps_dst_path }}"

##
# notes MD
##
kp_note_template: notes.md.j2
kp_note_filename: notes.md
kp_note_fullpath: "{{ kp_dst_fullpath }}/{{ kp_note_filename }}"