---

- name: Check
  ansible.builtin.assert:
    that:
    - keployr_git_url != ""
    - keployr_src_fullpath != ""
    fail_msg: "You must set keployr_git_url, keployr_src_fullpath variables!"

- name: Clear dir
  ansible.builtin.file:
    path: "{{ keployr_tmp_project_dir }}"
    state: absent
    force: yes

- name: "clone branch {{ keployr_git_branch }} of {{ keployr_git_url }} to {{ keployr_tmp_project_dir }}"
  ansible.builtin.shell:
    cmd: |
      git clone --depth=1 -b {{ keployr_git_branch }} {{ keployr_git_url }} {{ keployr_tmp_project_dir }}
      cd {{ keployr_tmp_project_dir }}
      {% if keployr_git_user_email != '' %}git config user.email "{{ keployr_git_user_email }}"{% endif %}
      {% if keployr_git_user != '' %}git config user.name "{{ keployr_git_user }}"{% endif %}
  register: clone_ret

- debug: msg="{{ clone_ret.stdout }}"

- name: Clean and create {{ keployr_dst_fullpath }} directory
  ansible.builtin.file:
    path: "{{ keployr_dst_fullpath }}"
    state: "{{ item }}"
  loop: ["absent", "directory"]

- name: Exist or create argoCD appSet {{ keployr_dst_gitops_apps_fullpath }} directory
  ansible.builtin.file:
    path: "{{ keployr_dst_gitops_apps_fullpath }}"
    state: directory

- name: Copy files from {{ keployr_src_fullpath }}, {{ keployr_src_gitops_apps_fullpath }}
  ansible.builtin.shell:
    cmd: |
      [ -d "{{ keployr_src_fullpath }}" ] && cp -r {{ keployr_src_fullpath }}/. {{ keployr_dst_fullpath }}
      [ -f "{{ keployr_src_gitops_apps_fullpath }}" ] && cp {{ keployr_src_gitops_apps_fullpath }} {{ keployr_dst_gitops_apps_fullpath }}/
      exit 0
  register: copy_ret

- debug: msg="{{ copy_ret.stdout }}"
- debug: msg="{{ copy_ret.stderr }}"

- name: Add note.md
  when: keployr_note_template != ""
  template:
    src: "{{ keployr_note_template }}"
    dest: "{{ keployr_note_fullpath }}"

- name: Commit & push
  ansible.builtin.shell:
    cmd: |
      git add .
      git status
      git commit -am "{{ keployr_git_commit_message }}"
      git push origin {{ keployr_git_branch }}
    chdir: "{{ keployr_tmp_project_dir }}"
  register: push_ret

- debug: msg="{{ push_ret.stdout }}"
- debug: msg="{{ push_ret.stderr }}"
