---

- name: Check dir exist
  ansible.builtin.file:
    path: "{{ kp_build_gitops_apps_dir }}"
    state: directory

- name: Build "argocd-app.yaml"
  ansible.builtin.template:
    src: "argocd_app.yaml.j2"
    dest: "{{ kp_build_gitops_apps_dir }}/{{ keployr_component | lower }}-app.yaml"
    mode: '0644'
  vars:
    argocd_source_path: "{{ kp_component_gitops_path }}"
