---

- name: "Check build dir {{ keployr_build_dir }} exists"
  file: path={{ keployr_build_dir }} state="directory"

- name: Remove component build dir
  ansible.builtin.file:
    path: "{{ keployr_build_dir }}"
    state: absent

- name: Prepare WIP folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
  - "{{ keployr_build_manifests_dir }}"
  - "{{ keployr_build_helm_dir }}"
  - "{{ keployr_build_kustomize_dir }}"
