---

- name: "Check build dir {{ kp_component_build_dir }} exists"
  file: path={{ kp_component_build_dir }} state="directory"

- name: Remove component build dir
  ansible.builtin.file:
    path: "{{ kp_component_build_dir }}"
    state: absent

- name: Prepare WIP folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
  - "{{ kp_build_manifests_dir }}"
  - "{{ kp_build_helm_dir }}"
  - "{{ kp_build_kustomize_dir }}"
