---

- name: Copy raw manifests
  when: kp_build_as_manifests
  shell:
    cmd: "mv {{ kp_build_manifests_dir }}/* {{ kp_component_build_dir }}/"

- name: Copy Helm resources
  when: not kp_build_as_manifests and (kp_helm_charts|count > 0 or kp_helm_values|count > 0)
  shell:
    cmd: "mv {{ kp_build_helm_dir }}/* {{ kp_component_build_dir }}/"

- name: Cleaning WIP folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
  - "{{ kp_build_manifests_dir }}"
  - "{{ kp_build_helm_dir }}"
  - "{{ kp_build_kustomize_dir }}"
