---

- 
  name: Copy extra YAML manifests
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ kp_build_manifests_dir }}/{{ item | basename }}"
  with_fileglob:
  - "{{ kp_src_manifests_dir }}/*"
