---

-
  name: Helm dependency
  shell:
    chdir: "{{ kp_build_helm_dir }}"
    cmd: helm dependency build

-
  name: Helm template
  environment:
    HELM_NAMESPACE: "{{ kp_k8s_namespace }}"
  shell:
    chdir: "{{ kp_build_helm_dir }}"
    cmd: helm template {{ kp_release_name }} . > all.yaml

-
  name: Copy all.yaml
  when: kp_build_as_manifests_single_file
  copy:
    dest: "{{ kp_build_manifests_dir }}/all.yaml"
    content: "{{ lookup('file', kp_build_helm_dir ~ '/all.yaml') }}"

-
  when: not kp_build_as_manifests_single_file
  ansible.builtin.include_tasks: helm_generate_manifests_multi.yaml
